let result=null,panoImage=new Image(),jawScene=null,toothScene=null,selectedTooth=null,toothTab='findings';
const $=id=>document.getElementById(id);
const DIRECT=()=> (result?.findings||[]).filter(f=>f.evidence_type==='direct');
const CANAL_CODES=new Set(['ROOT_CANAL_TREATED','UNDERFILLED_ROOT_CANAL','OVERFILLED_ROOT_CANAL','ENDO_POST']);
const CARIES_CODES=new Set(['CARIES','DEEP_CARIES','RECURRENT_CARIES']);
const RESTORE_CODES=new Set(['FILLING','CROWN','BRIDGE','INLAY_ONLAY','PONTIC','ENDO_POST']);
function showError(msg){const e=$('error');e.textContent=msg;e.style.display='block';setTimeout(()=>e.style.display='none',7000)}
function waitD3(){return new Promise(resolve=>{if(window.D3)return resolve(window.D3);window.addEventListener('d3-ready',()=>resolve(window.D3),{once:true})})}
function disposeScene(ctx){if(!ctx)return;cancelAnimationFrame(ctx.raf);ctx.ro?.disconnect();ctx.renderer?.dispose();ctx.host.innerHTML=''}
function findingsFor(t){return DIRECT().filter(f=>String(f.fdi||'')===String(t.fdi))}
function isUpper(fdi){return ['1','2'].includes(String(fdi)[0])}
async function analyze(){const file=$('file').files[0];if(!file){showError('Önce panoramik seç.');return}$('status').textContent='Analiz + anatomik 3D hazırlanıyor…';panoImage.src=URL.createObjectURL(file);await panoImage.decode();$('panoImg').src=panoImage.src;$('panoMini').classList.remove('hidden');const fd=new FormData();fd.append('image',file);const r=await fetch('/analyze',{method:'POST',headers:{'X-Vision-Key':$('key').value},body:fd});if(!r.ok){$('status').textContent='Analiz tamamlanamadı';showError(await r.text());return}result=await r.json();$('status').textContent=`${result.unique_fdi_count||result.tooth_count||0} diş • anatomik modeller yükleniyor…`;try{await renderJaw();$('status').textContent=`${result.unique_fdi_count||result.tooth_count||0} diş • 3D hazır`}catch(e){console.error(e);$('status').textContent='3D oluşturulamadı';showError(String(e))}}
function createBase(host){const {THREE,OrbitControls}=window.D3;host.innerHTML='';const scene=new THREE.Scene();scene.background=new THREE.Color(0x020304);const camera=new THREE.PerspectiveCamera(36,host.clientWidth/host.clientHeight,.01,100);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(host.clientWidth,host.clientHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;host.appendChild(renderer.domElement);scene.add(new THREE.HemisphereLight(0xe7efff,0x030406,2.6));const k=new THREE.DirectionalLight(0xffffff,4);k.position.set(3,4,5);scene.add(k);const rim=new THREE.DirectionalLight(0x728dff,2.2);rim.position.set(-4,2,-4);scene.add(rim);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;const ctx={host,scene,camera,renderer,controls,raf:0,ro:null};const loop=()=>{ctx.raf=requestAnimationFrame(loop);controls.update();renderer.render(scene,camera)};loop();ctx.ro=new ResizeObserver(()=>{camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();renderer.setSize(host.clientWidth,host.clientHeight)});ctx.ro.observe(host);return ctx}
async function loadToothObject(fdi,opacity=.98){const {THREE,OBJLoader}=window.D3;const loader=new OBJLoader();const obj=await new Promise((resolve,reject)=>loader.load(`/anatomy/tooth/${encodeURIComponent(fdi)}.obj`,resolve,undefined,reject));obj.traverse(n=>{if(n.isMesh){n.geometry.computeVertexNormals();n.material=new THREE.MeshPhysicalMaterial({color:0xf4f1e8,roughness:.26,metalness:0,clearcoat:.2,transparent:opacity<1,opacity,side:THREE.DoubleSide})}});return obj}
function archPosition(t,minX,maxX){const [x1,,x2]=t.bbox.map(Number),c=(x1+x2)/2,n=(c-minX)/Math.max(1,maxX-minX),s=(n-.5)*2;return{x:s*3.15,z:-.65+2.15*(1-s*s),rotY:-s*.62,upper:isUpper(t.fdi)}}
function patientScale(t,medianW,medianH){const [x1,y1,x2,y2]=t.bbox.map(Number),w=x2-x1,h=y2-y1;return{x:Math.max(.72,Math.min(1.35,w/medianW)),y:Math.max(.76,Math.min(1.30,h/medianH)),z:Math.max(.78,Math.min(1.18,(w/medianW)*.92))}}
function median(a){if(!a.length)return 1;const b=[...a].sort((x,y)=>x-y);return b[Math.floor(b.length/2)]}
function addBone(scene,upper){const {THREE}=window.D3,pts=[];for(let i=0;i<=40;i++){const s=-1+i/20;pts.push(new THREE.Vector3(s*3.35,upper?.95:-.95,-.72+2.23*(1-s*s)))}const curve=new THREE.CatmullRomCurve3(pts),geo=new THREE.TubeGeometry(curve,100,.38,16,false),mat=new THREE.MeshPhysicalMaterial({color:0x8aa7ff,transparent:true,opacity:.13,roughness:.2,transmission:.34,depthWrite:false});scene.add(new THREE.Mesh(geo,mat))}
function addMandibularCanal(scene){const {THREE}=window.D3,pts=[];for(let i=0;i<=40;i++){const s=-1+i/20;pts.push(new THREE.Vector3(s*3.05,-1.08,-.68+1.93*(1-s*s)))}const curve=new THREE.CatmullRomCurve3(pts),geo=new THREE.TubeGeometry(curve,90,.055,10,false),mat=new THREE.MeshStandardMaterial({color:0xff6d8b,emissive:0x7b102b,emissiveIntensity:.28,transparent:true,opacity:.86});scene.add(new THREE.Mesh(geo,mat))}
async function renderJaw(){await waitD3();disposeScene(jawScene);jawScene=createBase($('jaw3d'));const {scene,camera,controls,renderer}=jawScene;camera.position.set(0,.15,8.7);controls.target.set(0,0,.65);controls.minDistance=4.2;controls.maxDistance=13;const teeth=(result.teeth||[]).filter(t=>t.bbox&&/^\d{2}$/.test(String(t.fdi)));if(!teeth.length)throw new Error('FDI diş tespiti yok');const widths=teeth.map(t=>t.bbox[2]-t.bbox[0]),heights=teeth.map(t=>t.bbox[3]-t.bbox[1]),mw=median(widths),mh=median(heights),minX=Math.min(...teeth.map(t=>t.bbox[0])),maxX=Math.max(...teeth.map(t=>t.bbox[2]));addBone(scene,true);addBone(scene,false);addMandibularCanal(scene);const clickables=[];const loaded=await Promise.all(teeth.map(async t=>{try{return[t,await loadToothObject(t.fdi)]}catch(e){console.warn('anatomy',t.fdi,e);return[t,null]}}));for(const [t,obj] of loaded){if(!obj)continue;const p=archPosition(t,minX,maxX),s=patientScale(t,mw,mh);obj.scale.set(.62*s.x,.62*s.y,.62*s.z);obj.position.set(p.x,p.upper?.70:-.70,p.z);obj.rotation.y=p.rotY;if(p.upper)obj.rotation.z=Math.PI;obj.userData.tooth=t;obj.traverse(n=>{if(n.isMesh){n.userData.tooth=t;clickables.push(n)}});scene.add(obj)}const {THREE}=window.D3,ray=new THREE.Raycaster(),mouse=new THREE.Vector2();renderer.domElement.addEventListener('pointerdown',ev=>{const r=renderer.domElement.getBoundingClientRect();mouse.x=((ev.clientX-r.left)/r.width)*2-1;mouse.y=-((ev.clientY-r.top)/r.height)*2+1;ray.setFromCamera(mouse,camera);const hit=ray.intersectObjects(clickables,false)[0];if(hit?.object?.userData?.tooth)openTooth(hit.object.userData.tooth)})}
function cropTooth(t){const [x1,y1,x2,y2]=t.bbox.map(Number),w=Math.max(1,x2-x1),h=Math.max(1,y2-y1),padX=Math.max(18,w*.72),padY=Math.max(12,h*.16),sx=Math.max(0,x1-padX),sy=Math.max(0,y1-padY),sw=Math.min(panoImage.naturalWidth-sx,w+2*padX),sh=Math.min(panoImage.naturalHeight-sy,h+2*padY),c=$('crop');c.width=Math.max(1,Math.round(sw));c.height=Math.max(1,Math.round(sh));const ctx=c.getContext('2d');ctx.drawImage(panoImage,sx,sy,sw,sh,0,0,c.width,c.height);return{sx,sy,sw,sh,canvas:c,image:ctx.getImageData(0,0,c.width,c.height)}}
function percentile(v,p){if(!v.length)return 0;const a=[...v].sort((x,y)=>x-y);return a[Math.max(0,Math.min(a.length-1,Math.floor((a.length-1)*p)))]}
function grayAt(img,w,x,y){const i=(y*w+x)*4;return(img.data[i]+img.data[i+1]+img.data[i+2])/3}
function extractCanalPath(t,crop,findings){const canalFind=findings.find(f=>CANAL_CODES.has(f.finding_code));if(!canalFind)return null;const [tx1,ty1,tx2,ty2]=t.bbox.map(Number),tw=Math.max(1,tx2-tx1),th=Math.max(1,ty2-ty1),upper=isUpper(t.fdi),c=crop.canvas,img=crop.image;const fb=(canalFind.bbox||t.bbox).map(Number);let L=Math.max(0,Math.floor(Math.max(tx1,fb[0])-crop.sx)),R=Math.min(c.width-1,Math.ceil(Math.min(tx2,fb[2])-crop.sx));let T=Math.max(0,Math.floor(Math.max(ty1,fb[1])-crop.sy)),B=Math.min(c.height-1,Math.ceil(Math.min(ty2,fb[3])-crop.sy));if(R-L<5||B-T<8){L=Math.max(0,Math.floor(tx1-crop.sx));R=Math.min(c.width-1,Math.ceil(tx2-crop.sx));T=Math.max(0,Math.floor(ty1-crop.sy));B=Math.min(c.height-1,Math.ceil(ty2-crop.sy))}const rootCut=upper?Math.round(T+(B-T)*.72):Math.round(T+(B-T)*.28);if(upper)B=rootCut;else T=rootCut;const vals=[];for(let y=T;y<=B;y++)for(let x=L;x<=R;x++)vals.push(grayAt(img,c.width,x,y));const thr=Math.max(150,percentile(vals,.80));const rows=[];let prev=null;const ySeq=[];if(upper){for(let y=B;y>=T;y--)ySeq.push(y)}else{for(let y=T;y<=B;y++)ySeq.push(y)}for(const y of ySeq){const cand=[];for(let x=L;x<=R;x++){const g=grayAt(img,c.width,x,y);if(g>=thr&&(prev===null||Math.abs(x-prev)<=Math.max(7,(R-L)*.24)))cand.push([x,g])}if(!cand.length)continue;let sw=0,sx=0;for(const [x,g] of cand){const w=Math.max(1,g-thr+1);sw+=w;sx+=x*w}const cx=sx/sw;rows.push([cx,y]);prev=cx}if(rows.length<8)return null;const smooth=rows.map((p,i)=>{let sx=0,sy=0,n=0;for(let j=Math.max(0,i-4);j<=Math.min(rows.length-1,i+4);j++){sx+=rows[j][0];sy+=rows[j][1];n++}return[sx/n,sy/n]});const step=Math.max(2,Math.floor(smooth.length/14)),coarse=smooth.filter((_,i)=>i===0||i===smooth.length-1||i%step===0);const pts=coarse.map(([x,y])=>{const fx=x+crop.sx,fy=y+crop.sy,nx=((fx-(tx1+tx2)/2)/tw)*1.15,ry=(fy-ty1)/th,ny=upper?(-1.02+ry*1.92):(.90-ry*1.92);return[nx,ny,0]});let lenPx=0;for(let i=1;i<coarse.length;i++)lenPx+=Math.hypot(coarse[i][0]-coarse[i-1][0],coarse[i][1]-coarse[i-1][1]);const dx=coarse.at(-1)[0]-coarse[0][0],dy=coarse.at(-1)[1]-coarse[0][1],angle=Math.atan2(Math.abs(dx),Math.abs(dy))*180/Math.PI;let bend=0;for(let i=1;i<coarse.length-1;i++){const ax=coarse[i][0]-coarse[i-1][0],ay=coarse[i][1]-coarse[i-1][1],bx=coarse[i+1][0]-coarse[i][0],by=coarse[i+1][1]-coarse[i][1];const den=Math.hypot(ax,ay)*Math.hypot(bx,by);if(den>0){const cos=Math.max(-1,Math.min(1,(ax*bx+ay*by)/den));bend+=Math.acos(cos)}}const lengthRatio=lenPx/th,curvatureDeg=bend*180/Math.PI,reliable=coarse.length>=5&&lengthRatio>=.25&&lengthRatio<=1.12&&angle<=55&&curvatureDeg<=90;return{points:pts,lengthRatio,angleDeg:angle,curvatureDeg,source:canalFind.finding_code,reliable}}
function addCanalTube(scene,path){if(!path?.reliable||!path?.points?.length)return;const {THREE}=window.D3,pts=path.points.map(p=>new THREE.Vector3(p[0],p[1],p[2])),curve=new THREE.CatmullRomCurve3(pts),geo=new THREE.TubeGeometry(curve,Math.max(32,pts.length*3),.045,10,false),mat=new THREE.MeshStandardMaterial({color:0xff5267,emissive:0x9b1228,emissiveIntensity:.32,transparent:true,opacity:.96});scene.add(new THREE.Mesh(geo,mat))}
function addFindingPixels(scene,t,crop,findings){const {THREE}=window.D3,[tx1,ty1,tx2,ty2]=t.bbox.map(Number),tw=Math.max(1,tx2-tx1),th=Math.max(1,ty2-ty1),img=crop.image,c=crop.canvas;for(const f of findings){if(CANAL_CODES.has(f.finding_code)||!f.bbox)continue;const dark=CARIES_CODES.has(f.finding_code),bright=RESTORE_CODES.has(f.finding_code);if(!dark&&!bright)continue;const [a,b,d,e]=f.bbox.map(Number),L=Math.max(0,Math.floor(a-crop.sx)),R=Math.min(c.width-1,Math.ceil(d-crop.sx)),T=Math.max(0,Math.floor(b-crop.sy)),B=Math.min(c.height-1,Math.ceil(e-crop.sy));const vals=[];for(let y=T;y<=B;y+=2)for(let x=L;x<=R;x+=2)vals.push(grayAt(img,c.width,x,y));const lo=percentile(vals,.28),hi=percentile(vals,.72),arr=[];for(let y=T;y<=B;y+=2)for(let x=L;x<=R;x+=2){const g=grayAt(img,c.width,x,y);if(bright&&g<hi)continue;if(dark&&g>lo)continue;const fx=x+crop.sx,fy=y+crop.sy,nx=((fx-(tx1+tx2)/2)/tw)*1.15,ry=(fy-ty1)/th,ny=isUpper(t.fdi)?(-1.02+ry*1.92):(.90-ry*1.92);arr.push(nx,ny,.30)}if(!arr.length)continue;const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(arr.slice(0,5400),3));const color=dark?0xc91f34:0x59cfff;scene.add(new THREE.Points(geo,new THREE.PointsMaterial({color,size:.028,transparent:true,opacity:.92,depthWrite:false})))}}
async function openTooth(t){await waitD3();selectedTooth=t;toothTab='findings';$('detail').classList.add('open');$('detailTitle').textContent=`Diş ${t.fdi}`;document.querySelectorAll('[data-tooth-tab]').forEach(b=>b.classList.toggle('active',b.dataset.toothTab==='findings'));const findings=findingsFor(t),crop=cropTooth(t);$('chips').innerHTML='';if(!findings.length){const s=document.createElement('span');s.className='chip';s.textContent='Doğrudan bulgu yok';$('chips').appendChild(s)}else findings.forEach(f=>{const s=document.createElement('span');s.className='chip';s.textContent=f.label||f.finding_code;$('chips').appendChild(s)});disposeScene(toothScene);toothScene=createBase($('tooth3d'));const {scene,camera,controls}=toothScene;camera.position.set(0,0,3.8);controls.target.set(0,0,0);controls.minDistance=1.7;controls.maxDistance=6;const obj=await loadToothObject(t.fdi,.30);obj.traverse(n=>{if(n.isMesh)n.material=new window.D3.THREE.MeshPhysicalMaterial({color:0xe9f1ff,transparent:true,opacity:.27,roughness:.12,transmission:.32,depthWrite:false,side:window.D3.THREE.DoubleSide})});scene.add(obj);const inner=await loadToothObject(t.fdi,.12);inner.scale.set(.83,.83,.83);inner.traverse(n=>{if(n.isMesh)n.material=new window.D3.THREE.MeshPhysicalMaterial({color:0xf4b4d5,transparent:true,opacity:.13,roughness:.2,depthWrite:false,side:window.D3.THREE.DoubleSide})});scene.add(inner);const path=extractCanalPath(t,crop,findings);addCanalTube(scene,path);addFindingPixels(scene,t,crop,findings);if(path?.reliable){$('metrics').textContent=`Filmden izlenen kanal: uzunluk ≈ diş boyunun ${(path.lengthRatio*100).toFixed(0)}%’i • eksenden sapma ${path.angleDeg.toFixed(1)}° • toplam eğrilik ${path.curvatureDeg.toFixed(1)}°. Bukkolingual derinlik panoramikten ölçülmez; kanal mesh merkez düzlemine yerleştirilir.`}else if(path){$('metrics').textContent='Filmde kanal tedavisi bulgusu var; ancak kanal hattı sayısal ölçüm için yeterince güvenilir çıkarılamadı. Geçersiz uzunluk/eğrilik değeri gösterilmedi.'}else{$('metrics').textContent='Bu dişte filmden izlenebilir kanal dolgusu hattı çıkarılmadı. Panoramikten bukkolingual derinlik üretilmez.'}renderToothSheet()}

function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function renderToothSheet(){
  const body=$('toothSheetBody');if(!body||!selectedTooth)return;
  const fs=findingsFor(selectedTooth);
  if(toothTab==='findings'){
    body.innerHTML='<div class="sheet-note">Bu dişe ait görüntü motoru bulguları.</div>'+(fs.length?'<div class="finding-list">'+fs.map(f=>'<div class="finding-card"><div class="finding-main"><div class="finding-title">'+esc(f.label||f.finding_code||'Bulgu')+'</div><div class="finding-sub">'+esc(f.description||f.explanation||('Diş '+selectedTooth.fdi+' ile ilişkilendirilen görüntü bulgusu.'))+'</div></div></div>').join('')+'</div>':'<div class="empty-card">Bu diş için gösterilecek bulgu yok.</div>');
    return;
  }
  if(toothTab==='treatments'){
    body.innerHTML='<div class="treatment-box"><div class="sheet-note">Klinik değerlendirme yalnız siz istediğinizde başlatılır. Seçili diş: '+esc(selectedTooth.fdi)+'</div><button id="toothAnalyze" class="analysis-action">Analiz Et</button><div id="toothAnalysisResult" class="treatment-result"></div></div>';
    $('toothAnalyze').onclick=()=>{const detail={fdi:selectedTooth.fdi,findings:fs};window.dispatchEvent(new CustomEvent('dental-ai:analyze-tooth',{detail}));if(window.parent&&window.parent!==window)window.parent.postMessage({type:'dental-ai:analyze-tooth',...detail},location.origin);const out=$('toothAnalysisResult');out.innerHTML='<div class="result-block"><b>Analiz hazırlanıyor</b>Seçili dişin klinik değerlendirmesi başlatıldı.</div>'};
    return;
  }
  body.innerHTML='<div class="view-list"><button class="view-toggle"><span>Tek diş 3D</span><span>Açık</span></button><button class="view-toggle"><span>Panoramik kesit</span><span>İsteğe bağlı</span></button><div class="sheet-note">Bu görünüm seçili dişe odaklanır; genel çene görünümüne Geri ile dönebilirsiniz.</div></div>';
}
document.querySelectorAll('[data-tooth-tab]').forEach(b=>b.onclick=()=>{toothTab=b.dataset.toothTab;document.querySelectorAll('[data-tooth-tab]').forEach(x=>x.classList.toggle('active',x===b));renderToothSheet()});
$('run').onclick=analyze;$('close').onclick=()=>$('detail').classList.remove('open');

window.addEventListener('message',async ev=>{
  if(ev.origin!==location.origin)return;
  const d=ev.data||{};
  if(d.type==='dental-ai:patient-analysis'&&d.assetUrl){
    try{
      const top=$('file')?.closest('.top');if(top)top.style.display='none';
      const ir=await fetch(d.assetUrl,{credentials:'same-origin'});if(!ir.ok)throw new Error('Görüntü alınamadı');
      const blob=await ir.blob();panoImage.src=URL.createObjectURL(blob);await panoImage.decode();$('panoImg').src=panoImage.src;$('panoMini').classList.remove('hidden');
      const vr=await fetch(d.visionUrl,{credentials:'same-origin',cache:'no-store'});if(!vr.ok){if(vr.status===202){$('status').textContent='Görüntü motoru çalışıyor…';return}throw new Error('Kayıtlı motor sonucu alınamadı')}
      const snap=await vr.json();result=snap.result||snap;
      $('status').textContent='Anatomik 3D hazırlanıyor…';
      await renderJaw();$('status').textContent='3D hazır';
    }catch(e){$('status').textContent='Analiz tamamlanamadı';showError(String(e))}
  }
  if(d.type==='dental-ai:tooth-analysis-started'&&!d.ok)showError(d.error||'Klinik analiz başlatılamadı');
});
