"""Extended dental retrieval vocabulary.

Static data only: no model/provider calls and no clinical answer facts.
"""
EXTENDED_SPECIALTY_CONCEPTS = {
    "endodontics": (
        ("apexification", "apeksifikasyon", ("apexification",), "procedure"),
        ("apexogenesis", "apeksogenez", ("apexogenesis",), "procedure"),
        ("regenerative_endodontics", "rejeneratif endodonti", ("regenerative endodontics", "revascularization"), "procedure"),
        ("gutta_percha", "güta-perka", ("gutta-percha", "gutta percha"), "material"),
        ("sodium_hypochlorite", "sodyum hipoklorit", ("sodium hypochlorite", "NaOCl"), "material"),
        ("edta", "EDTA", ("ethylenediaminetetraacetic acid",), "material"),
    ),
    "periodontology": (
        ("gingival_recession", "gingival çekilme", ("gingival recession", "dişeti çekilmesi"), "finding"),
        ("gtr", "yönlendirilmiş doku rejenerasyonu", ("guided tissue regeneration", "GTR"), "procedure"),
        ("gbr", "yönlendirilmiş kemik rejenerasyonu", ("guided bone regeneration", "GBR"), "procedure"),
        ("root_planing", "kök yüzeyi düzleştirme", ("root planing",), "procedure"),
    ),
    "oral_surgery": (
        ("mronj", "ilaç ilişkili çene osteonekrozu", ("MRONJ", "medication-related osteonecrosis of the jaw"), "diagnosis"),
        ("sinus_lift", "sinüs tabanı yükseltme", ("sinus lift", "sinus floor augmentation"), "procedure"),
        ("ian_injury", "inferior alveolar sinir yaralanması", ("inferior alveolar nerve injury", "IAN injury"), "complication"),
        ("trismus", "trismus", ("trismus",), "complication"),
    ),
    "radiology": (
        ("bitewing", "bitewing radyografi", ("bitewing", "interproximal radiograph"), "imaging"),
        ("periapical_radiograph", "periapikal radyografi", ("periapical radiograph", "intraoral periapical"), "imaging"),
        ("cortication", "kortikasyon", ("cortication", "corticated border"), "finding"),
        ("trabeculation", "trabekülasyon", ("trabeculation", "trabecular pattern"), "finding"),
    ),
    "prosthodontics": (
        ("complete_denture", "tam protez", ("complete denture", "full denture"), "appliance"),
        ("rpd", "hareketli bölümlü protez", ("removable partial denture", "RPD"), "appliance"),
        ("fpd", "sabit bölümlü protez", ("fixed partial denture", "FPD"), "appliance"),
        ("kennedy_classification", "Kennedy sınıflaması", ("Kennedy classification",), "classification"),
        ("polyether", "polieter", ("polyether",), "material"),
    ),
    "restorative": (
        ("rmgic", "rezin modifiye cam iyonomer", ("resin-modified glass ionomer", "RMGIC"), "material"),
        ("polymerization", "polimerizasyon", ("polymerization", "light curing"), "procedure"),
        ("microleakage", "mikrosızıntı", ("microleakage",), "finding"),
        ("c_factor", "C-faktörü", ("C-factor", "configuration factor"), "measurement"),
    ),
    "pediatric_dentistry": (
        ("mih", "molar insizor hipomineralizasyonu", ("MIH", "molar incisor hypomineralization"), "diagnosis"),
        ("ssc", "paslanmaz çelik kron", ("stainless steel crown", "SSC"), "appliance"),
        ("mixed_dentition", "karışık dişlenme", ("mixed dentition",), "classification"),
    ),
    "oral_pathology": (
        ("oscc", "oral skuamöz hücreli karsinom", ("oral squamous cell carcinoma", "OSCC"), "diagnosis"),
        ("odontogenic_keratocyst", "odontojenik keratokist", ("odontogenic keratocyst", "OKC"), "diagnosis"),
        ("ameloblastoma_ext", "ameloblastoma", ("ameloblastoma",), "diagnosis"),
        ("mucocele", "mukosel", ("mucocele",), "diagnosis"),
    ),
    "dental_anesthesia": (
        ("lidocaine", "lidokain", ("lidocaine",), "material"),
        ("articaine", "artikain", ("articaine",), "material"),
        ("mepivacaine", "mepivakain", ("mepivacaine",), "material"),
        ("prilocaine", "prilokain", ("prilocaine",), "material"),
        ("epinephrine", "epinefrin", ("epinephrine", "adrenaline"), "material"),
        ("ianb", "inferior alveolar sinir bloğu", ("inferior alveolar nerve block", "IANB"), "procedure"),
        ("infiltration_anesthesia", "infiltrasyon anestezisi", ("infiltration anesthesia",), "procedure"),
        ("intraligamentary_anesthesia", "intraligamenter anestezi", ("intraligamentary anesthesia",), "procedure"),
        ("intrapulpal_anesthesia", "intrapulpal anestezi", ("intrapulpal anesthesia",), "procedure"),
        ("anesthetic_paresthesia", "lokal anestezi parestezisi", ("paresthesia", "parestezi"), "complication"),
    ),
    "oral_anatomy_histology": (
        ("enamel", "mine", ("enamel", "enamel tissue"), "tissue"),
        ("dentin", "dentin", ("dentine",), "tissue"),
        ("cementum", "sement", ("cementum", "dental cementum"), "tissue"),
        ("dental_pulp", "diş pulpası", ("dental pulp", "pulpa"), "tissue"),
        ("periodontal_ligament", "periodontal ligament", ("PDL", "periodontal membrane"), "tissue"),
        ("junctional_epithelium", "birleşim epiteli", ("junctional epithelium", "JE"), "tissue"),
        ("odontoblast", "odontoblast", ("odontoblasts",), "cell"),
        ("ameloblast", "ameloblast", ("ameloblasts",), "cell"),
        ("cementoblast", "sementoblast", ("cementoblast",), "cell"),
        ("odontogenesis", "odontogenez", ("odontogenesis", "tooth development"), "development"),
        ("amelogenesis", "amelogenez", ("amelogenesis", "enamel formation"), "development"),
        ("dentinogenesis", "dentinogenez", ("dentinogenesis", "dentin formation"), "development"),
        ("hertwig_root_sheath", "Hertwig epitel kök kını", ("Hertwig epithelial root sheath", "HERS"), "anatomy"),
        ("dental_lamina", "dental lamina", ("dental lamina", "diş laminası"), "anatomy"),
        ("enamel_organ", "mine organı", ("enamel organ",), "anatomy"),
    ),
    "dental_pharmacology": (
        ("nsaid", "NSAİİ", ("NSAID", "nonsteroidal anti-inflammatory drug", "non-steroidal anti-inflammatory drug"), "drug_class"),
        ("paracetamol", "parasetamol", ("paracetamol", "acetaminophen"), "drug"),
        ("amoxicillin", "amoksisilin", ("amoxicillin",), "drug"),
        ("amoxicillin_clavulanate", "amoksisilin klavulanat", ("amoxicillin clavulanate", "co-amoxiclav"), "drug"),
        ("metronidazole", "metronidazol", ("metronidazole",), "drug"),
        ("clindamycin", "klindamisin", ("clindamycin",), "drug"),
        ("macrolide", "makrolid", ("macrolide", "macrolide antibiotic"), "drug_class"),
        ("bisphosphonate", "bisfosfonat", ("bisphosphonate", "bisphosphonates"), "drug_class"),
        ("antiresorptive", "antirezorptif", ("antiresorptive", "anti-resorptive"), "drug_class"),
        ("anticoagulant", "antikoagülan", ("anticoagulant", "blood thinner"), "drug_class"),
        ("antiplatelet", "antiplatelet", ("antiplatelet agent", "antiaggregant"), "drug_class"),
    ),
    "dental_materials": (
        ("amalgam", "dental amalgam", ("amalgam",), "material"),
        ("resin_composite", "kompozit rezin", ("resin composite", "composite resin"), "material"),
        ("calcium_hydroxide", "kalsiyum hidroksit", ("calcium hydroxide", "CaOH2"), "material"),
        ("mta_material", "mineral trioksit agregat", ("mineral trioxide aggregate", "MTA"), "material"),
        ("biodentine", "Biodentine", ("biodentine",), "material"),
        ("zinc_oxide_eugenol", "çinko oksit öjenol", ("zinc oxide eugenol", "ZOE"), "material"),
        ("zinc_phosphate", "çinko fosfat siman", ("zinc phosphate cement",), "material"),
        ("resin_cement", "rezin siman", ("resin cement",), "material"),
        ("ceramic", "dental seramik", ("dental ceramic", "ceramic"), "material"),
        ("zirconia", "zirkonya", ("zirconia", "zirconium dioxide"), "material"),
        ("lithium_disilicate", "lityum disilikat", ("lithium disilicate",), "material"),
        ("pmma", "PMMA", ("polymethyl methacrylate", "polimetil metakrilat"), "material"),
        ("impression_compound", "termoplastik ölçü maddesi", ("impression compound",), "material"),
    ),
    "dental_indices_measurements": (
        ("dmft", "DMFT", ("DMF-T", "decayed missing filled teeth"), "index"),
        ("dmfs", "DMFS", ("DMF-S", "decayed missing filled surfaces"), "index"),
        ("deft", "deft", ("def-t",), "index"),
        ("plaque_index", "plak indeksi", ("plaque index", "Silness Loe plaque index"), "index"),
        ("gingival_index", "gingival indeks", ("gingival index", "Loe Silness gingival index"), "index"),
        ("cpi", "CPI", ("community periodontal index", "CPITN"), "index"),
        ("psr", "PSR", ("periodontal screening and recording",), "index"),
        ("papilla_bleeding_index", "papil kanama indeksi", ("papilla bleeding index", "PBI"), "index"),
        ("mobility_grade", "diş mobilitesi", ("tooth mobility", "Miller mobility"), "classification"),
        ("furcation_classification", "furkasyon sınıflaması", ("Hamp classification", "Glickman classification"), "classification"),
        ("perio_stage", "periodontitis evresi", ("periodontitis stage", "staging"), "classification"),
        ("perio_grade", "periodontitis derecesi", ("periodontitis grade", "grading"), "classification"),
        ("asa_classification", "ASA sınıflaması", ("ASA physical status", "ASA classification"), "classification"),
        ("mallampati", "Mallampati sınıflaması", ("Mallampati score", "Mallampati classification"), "classification"),
        ("kennedy", "Kennedy sınıflaması", ("Kennedy classification",), "classification"),
        ("black_classification", "Black kavite sınıflaması", ("G.V. Black classification", "Black classification"), "classification"),
        ("icdas", "ICDAS", ("International Caries Detection and Assessment System",), "classification"),
        ("periapical_index", "periapikal indeks", ("periapical index", "PAI"), "index"),
    ),
    "oral_surgery_pathology_radiology": (
        ("alveolar_osteitis", "alveolar osteit", ("dry socket", "alveolitis sicca"), "complication"),
        ("oroantral_fistula", "oroantral fistül", ("oroantral fistula", "OAF"), "complication"),
        ("vertical_root_fracture", "vertikal kök kırığı", ("vertical root fracture", "VRF"), "diagnosis"),
        ("external_cervical_resorption", "eksternal servikal rezorpsiyon", ("external cervical resorption", "ECR"), "diagnosis"),
        ("perforation", "kök perforasyonu", ("root perforation", "perforation"), "complication"),
        ("separated_instrument", "kırık alet", ("separated instrument", "instrument separation"), "complication"),
        ("oral_erythroplakia", "eritroplaki", ("erythroplakia",), "diagnosis"),
        ("oral_potentially_malignant_disorder", "oral potansiyel malign bozukluk", ("oral potentially malignant disorder", "OPMD"), "classification"),
        ("clinicopathologic_correlation", "klinikopatolojik korelasyon", ("clinicopathologic correlation",), "assessment"),
        ("antibiotic_stewardship", "antibiyotik yönetimi", ("antibiotic stewardship",), "principle"),
        ("systemic_involvement", "sistemik tutulum", ("systemic involvement", "fever malaise"), "finding"),
    ),
}
